---
version: "3.3"

services:
  controller: 
    container_name: controller
    hostname: controller
    image: almalinux:9
    entrypoint: ['sleep', 'infinity'] 
    networks: 
      - lab  
  node1:
    container_name: node1
    hostname: node1
    image: almalinux:9
    entrypoint: ['sleep', 'infinity'] 
    networks: 
      - lab
  node2: 
    container_name: node2
    hostname: node2
    image: almalinux:9
    entrypoint: ['sleep', 'infinity'] 
    networks: 
      - lab

networks:
  lab:
...