---
apiVersion: v1
kind: Pod
metadata:
  name: controller
spec:
  containers:
    - name: shell
      image: almalinux:8
      command: ['sleep', 'infinity']
...
---
apiVersion: v1
kind: Pod
metadata:
  name: node1
spec:
  containers:
    - name: shell
      image: almalinux:8
      command: ['sleep', 'infinity']
...
---
apiVersion: v1
kind: Pod
metadata:
  name: node2
spec:
  containers:
    - name: shell
      image: almalinux:8
      command: ['sleep', 'infinity']
...